# Generated by Django 2.2.3 on 2019-07-07 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='Name',
            new_name='name',
        ),
    ]
