# Generated by Django 2.2.3 on 2019-07-07 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190707_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='email',
        ),
        migrations.RemoveField(
            model_name='login',
            name='major',
        ),
        migrations.RemoveField(
            model_name='login',
            name='name',
        ),
        migrations.RemoveField(
            model_name='login',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='login',
            name='stu_id',
        ),
        migrations.RemoveField(
            model_name='login',
            name='th',
        ),
    ]
